version: "3"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      APP_PORT: 8000
      DB_HOST: db
      DB_USER: user_1
      DB_NAME: database_1
      DB_PASSWORD: password_1
      DB_PORT: 3307
      WAIT_HOSTS: db:3307
      WAIT_HOSTS_TIMEOUT: 60
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_1
      MYSQL_USER: user_1
      MYSQL_PASSWORD: password_1
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    volumes:
      - "./db/preset.sql:/docker-entrypoint-initdb.d/preset.sql"
