CREATE TABLE Deals (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  clientUsername VARCHAR(100) NOT NULL,
  gemName VARCHAR(100) NOT NULL,
  gemQuantity TINYINT NOT NULL,
  total INT NOT NULL,
  date DATE NOT NULL
);
